In [1]:
from  datetime import datetime, timedelta
import gc
import numpy as np, pandas as pd
import lightgbm as lgb

#Hiển thị max 50 cột
pd.options.display.max_columns = 50

# Trỏ đường dẫn để gọi file trong thư mục src
import sys, os
sys.path.append(os.path.abspath('../src'))

from dataPreprocessing import create_dt, create_fea

In [2]:
#Định nghĩa dữ liệu cho từng cột phân loại
CAL_DTYPES={"event_name_1": "category", "event_name_2": "category", "event_type_1": "category", 
         "event_type_2": "category", "weekday": "category", 'wm_yr_wk': 'int16', "wday": "int16",
        "month": "int16", "year": "int16", "snap_CA": "float32", 'snap_TX': 'float32', 'snap_WI': 'float32' }

#Định nghĩa dữ liệu cho câc cột lien quan đến giá
PRICE_DTYPES = {"store_id": "category", "item_id": "category", "wm_yr_wk": "int16","sell_price":"float32" }

#Ngày bắt đầu lấy dữ liệu
FIRST_DAY = 350

#Định nghĩa một số biến đầu vào
h = 28 
max_lags = 57
tr_last = 1913
fday = datetime(2016,4, 25) 
fday

datetime.datetime(2016, 4, 25, 0, 0)

In [3]:
#Convert dữ liệu sang dạng long
df = create_dt(is_train=True, first_day= FIRST_DAY, nrows=None, price_dt = PRICE_DTYPES, cal_dt = CAL_DTYPES)
df.shape

(40718219, 22)

In [4]:
#Load phân loại deamand đã có từ trước
df_demandType = pd.read_csv("../dataset/result/demand_classification.csv")
df_demandType.head()

                            id   ADI   CV2                   Category
0  FOODS_1_001_CA_1_validation  2.29  0.26  Intermittent (Ngắt quãng)
1  FOODS_1_001_CA_2_validation  1.93  0.46  Intermittent (Ngắt quãng)
2  FOODS_1_001_CA_3_validation  2.23  0.50             Lumpy (Cục bộ)
3  FOODS_1_001_CA_4_validation  3.87  0.24  Intermittent (Ngắt quãng)
4  FOODS_1_001_TX_1_validation  3.06  0.29  Intermittent (Ngắt quãng)

In [5]:
#Add demand feature vào df
def add_demandFeature(demand_dir = "../dataset/result/demand_classification.csv", data = None):
    #Load phân loại deamand đã có từ trước
    df_demandType = pd.read_csv(demand_dir)

    # Merge df with df_demandType to add 'Category' column
    df = data

    # Merge df with df_demandType to add 'Category' column
    df = df.merge(df_demandType[['id', 'Category']], on='id', how='left')

    # Perform one-hot encoding on 'Category' column
    df = pd.get_dummies(df, columns=['Category'], prefix='cat')

    return df

df = add_demandFeature(data = df)

df.head()

,id,item_id,dept_id,store_id,cat_id,state_id,d,sales,date,wm_yr_wk,weekday,wday,month,year,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price,cat_Erratic (Thất thường),cat_Intermittent (Ngắt quãng),cat_Lumpy (Cục bộ),cat_Smooth (Đều đặn)
0,HOBBIES_1_002_CA_1_validation,1,0,0,0,0,d_350,0.0,2012-01-13,11150,0,7,1,2012,0,0,0,0,0.0,1.0,0.0,3.97,False,True,False,False
1,HOBBIES_1_004_CA_1_validation,3,0,0,0,0,d_350,2.0,2012-01-13,11150,0,7,1,2012,0,0,0,0,0.0,1.0,0.0,4.34,False,True,False,False
2,HOBBIES_1_005_CA_1_validation,4,0,0,0,0,d_350,0.0,2012-01-13,11150,0,7,1,2012,0,0,0,0,0.0,1.0,0.0,2.48,False,True,False,False
3,HOBBIES_1_008_CA_1_validation,7,0,0,0,0,d_350,0.0,2012-01-13,11150,0,7,1,2012,0,0,0,0,0.0,1.0,0.0,0.50,False,False,True,False
4,HOBBIES_1_009_CA_1_validation,8,0,0,0,0,d_350,2.0,2012-01-13,11150,0,7,1,2012,0,0,0,0,0.0,1.0,0.0,1.77,False,True,False,False

In [6]:
#Làm giàu đặc trưng
create_fea(df ,lags_fe = [7, 28, 56], wins_fe = [7, 28], std_fe = [28], 
           price_lags_fe = [7], price_wins_fe = [28], price_std_fe = [28])
df.shape

(40718219, 44)

In [7]:
#Peview một số dòng đầu
df.tail()

,id,item_id,dept_id,store_id,cat_id,state_id,d,sales,date,wm_yr_wk,weekday,wday,month,year,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,sell_price,cat_Erratic (Thất thường),cat_Intermittent (Ngắt quãng),cat_Lumpy (Cục bộ),cat_Smooth (Đều đặn),lag_7,lag_28,lag_56,rmean_7_7,rmean_28_7,rmean_56_7,rmean_7_28,rmean_28_28,rmean_56_28,rstd_7_28,rstd_28_28,rstd_56_28,price_lag_7,price_rmean_7_28,price_rstd_7_28,week,quarter,mday
40718214,FOODS_3_823_WI_3_validation,3044,6,9,2,2,d_1913,1.0,2016-04-24,11613,3,2,4,2016,0,0,0,0,0.0,0.0,0.0,2.98,False,True,False,False,0.0,0.0,1.0,0.571429,0.000000,0.285714,0.142857,0.250000,0.750000,0.524531,0.585314,1.109721,2.98,2.980000,0.000000e+00,16,2,24
40718215,FOODS_3_824_WI_3_validation,3045,6,9,2,2,d_1913,0.0,2016-04-24,11613,3,2,4,2016,0,0,0,0,0.0,0.0,0.0,2.48,False,True,False,False,0.0,0.0,0.0,0.285714,0.000000,0.000000,0.285714,0.000000,0.000000,0.534522,0.000000,0.000000,2.48,2.274286,2.418973e-01,16,2,24
40718216,FOODS_3_825_WI_3_validation,3046,6,9,2,2,d_1913,0.0,2016-04-24,11613,3,2,4,2016,0,0,0,0,0.0,0.0,0.0,3.98,False,True,False,False,0.0,1.0,0.0,1.000000,0.714286,0.428571,0.928571,1.250000,0.642857,1.184110,0.927961,0.731021,3.98,3.980000,5.384158e-08,16,2,24
40718217,FOODS_3_826_WI_3_validation,3047,6,9,2,2,d_1913,3.0,2016-04-24,11613,3,2,4,2016,0,0,0,0,0.0,0.0,0.0,1.28,False,True,False,False,1.0,4.0,0.0,0.714286,1.571429,0.000000,1.035714,1.250000,0.892857,1.070899,1.075829,1.165532,1.28,1.280000,0.000000e+00,16,2,24
40718218,FOODS_3_827_WI_3_validation,3048,6,9,2,2,d_1913,0.0,2016-04-24,11613,3,2,4,2016,0,0,0,0,0.0,0.0,0.0,1.00,False,True,False,False,0.0,5.0,0.0,0.000000,2.428571,1.285714,1.678571,1.964286,1.571429,1.925532,1.752927,1.989390,1.00,1.000000,0.000000e+00,16,2,24

In [8]:
#Drop các dòng không có dữ liệU
df.dropna(inplace = True)
df.shape

(38187637, 44)

In [9]:
#Các cột phân loại
cat_feats = ['item_id', 'dept_id','store_id', 'cat_id', 'state_id'] + \
["event_name_1", "event_name_2", "event_type_1", "event_type_2"] + \
['cat_Erratic (Thất thường)', 'cat_Intermittent (Ngắt quãng)', 'cat_Lumpy (Cục bộ)', 'cat_Smooth (Đều đặn)']
#Các cột không sử dụng
useless_cols = ["id", "date", "sales","d", "wm_yr_wk", "weekday"]

#Định nghĩa param cho thuật toán LightGBM
params = {
        "objective" : "poisson",
        "metric" :"rmse",
        "force_row_wise" : True,
        "learning_rate" : 0.075,
#         "sub_feature" : 0.8,
        "sub_row" : 0.75,
        "bagging_freq" : 1,
        "lambda_l2" : 0.1,
         "nthread" : 8,
        "metric": ["rmse"],
    'verbosity': 1,
    'num_iterations' : 4000,
    'num_leaves': 128,
    "min_data_in_leaf": 100,
    "device": "cpu",
    "early_stopping_round": 100
}

#Các cột sử dụng trong tập train (ngoại trừ những cột ko dùng ĐN ở trên)
train_cols = df.columns[~df.columns.isin(useless_cols)]

In [10]:
i = 0
for store, df_store in df.groupby("store_id"):

    print(f"Processing store {store}...")
    X_train = df_store[train_cols]
    y_train = df_store["sales"]

    #Cố định seed random
    np.random.seed(777)

    print(f"Create fake valid data for store {store}...")
    #Fake ra 30 000 index cho tập fake valid
    fake_valid_inds = np.random.choice(X_train.index.values, 30000, replace = False)

    #Index còn lại làm cho tập train
    train_inds = np.setdiff1d(X_train.index.values, fake_valid_inds)

    #Tập dữ liệu train
    train_data = lgb.Dataset(X_train.loc[train_inds] , label = y_train.loc[train_inds], 
                            categorical_feature=cat_feats, free_raw_data=False)

    #Tập dữ liệU valid fake
    fake_valid_data = lgb.Dataset(X_train.loc[fake_valid_inds], label = y_train.loc[fake_valid_inds],
                                categorical_feature=cat_feats,
                    free_raw_data=False)
    
    print(f"Done creating fake valid data for store {store}...")

    #Giải phóng bộ nhớ
    if i == 0:
        del df, X_train, y_train, fake_valid_inds,train_inds ; gc.collect()
        i += 1
    else:
        del X_train, y_train, fake_valid_inds,train_inds ; gc.collect()

    print(f"Training model for store {store}...")
    #Train mô hình
    m_lgb = lgb.train(params, train_data, valid_sets = [fake_valid_data],  callbacks=[lgb.log_evaluation(20)])

    #Save mô hình
    m_lgb.save_model(f"../dataset/result/model/model_store_{store}.lgb")

Processing store 0...
Create fake valid data for store 0...
Done creating fake valid data for store 0...
Training model for store 0...
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Total Bins 6685
[LightGBM] [Info] Number of data points in the train set: 3852898, number of used features: 36
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Start training from score 0.445571
Training until validation scores don't improve for 100 rounds
[20]	valid_0's rmse: 3.79839
[40]	valid_0's rmse: 3.52815
[60]	valid_0's rmse: 3.45871
[80]	valid_0's rmse: 3.42854
[100]	valid_0's rmse: 3.41511
[120]	valid_0's rmse: 3.40663
[140]	valid_0's rmse: 3.39968
[160]	valid_0's rmse: 3.39505
[180]	valid_0's rmse: 3.38807
[200]	valid_0's rmse: 3.3807
[220]	valid_0's rmse: 3.37837
[240]	valid_0's rmse: 3.37518
[260]	valid_0's rmse: 3.36891
[280]	valid_0's rmse: 3.36645
[300]	valid_0's rmse: 3.36268
[320]	valid_0's rmse: 3.36112
[340]	valid_0's rmse: 3.35885
[360]	valid_0's rmse: 3.35404
[380]	valid_0's rmse: 3.34886
[400]	valid_0's rmse: 3.34962
[420]	valid_0's rmse: 3.34868
[440]	valid_0's rmse: 3.34739
[460]	valid_0's rmse: 3.34689
[480]	valid_0's rmse: 3.34508
[500]	valid_0's rmse: 3.3436
[520]	valid_0's rmse: 3.34265
[540]	valid_0's rmse: 3.34244
[560]	valid_0's rmse: 3.34058
[580]	valid_0's rmse: 3.34236
[600]	valid_0's rmse: 3.34052
[620]	valid_0's rmse: 3.33885
[640]	valid_0's rmse: 3.33766
[660]	valid_0's rmse: 3.33497
[680]	valid_0's rmse: 3.33361
[700]	valid_0's rmse: 3.33432
[720]	valid_0's rmse: 3.3331
[740]	valid_0's rmse: 3.33555
[760]	valid_0's rmse: 3.33505
[780]	valid_0's rmse: 3.33716
[800]	valid_0's rmse: 3.33817
[820]	valid_0's rmse: 3.33749
Early stopping, best iteration is:
[721]	valid_0's rmse: 3.33304
Processing store 1...
Create fake valid data for store 1...
Done creating fake valid data for store 1...
Training model for store 1...
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Total Bins 6517
[LightGBM] [Info] Number of data points in the train set: 3505060, number of used features: 36
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Start training from score 0.205436
Training until validation scores don't improve for 100 rounds
[20]	valid_0's rmse: 2.2395
[40]	valid_0's rmse: 2.00387
[60]	valid_0's rmse: 1.94201
[80]	valid_0's rmse: 1.92157
[100]	valid_0's rmse: 1.91103
[120]	valid_0's rmse: 1.9065
[140]	valid_0's rmse: 1.90225
[160]	valid_0's rmse: 1.89828
[180]	valid_0's rmse: 1.89283
[200]	valid_0's rmse: 1.88845
[220]	valid_0's rmse: 1.88727
[240]	valid_0's rmse: 1.88527
[260]	valid_0's rmse: 1.88129
[280]	valid_0's rmse: 1.87933
[300]	valid_0's rmse: 1.87758
[320]	valid_0's rmse: 1.87624
[340]	valid_0's rmse: 1.87593
[360]	valid_0's rmse: 1.87544
[380]	valid_0's rmse: 1.87183
[400]	valid_0's rmse: 1.87092
[420]	valid_0's rmse: 1.86972
[440]	valid_0's rmse: 1.86729
[460]	valid_0's rmse: 1.86614
[480]	valid_0's rmse: 1.86519
[500]	valid_0's rmse: 1.86421
[520]	valid_0's rmse: 1.86227
[540]	valid_0's rmse: 1.86084
[560]	valid_0's rmse: 1.86088
[580]	valid_0's rmse: 1.85971
[600]	valid_0's rmse: 1.85812
[620]	valid_0's rmse: 1.85644
[640]	valid_0's rmse: 1.85476
[660]	valid_0's rmse: 1.85443
[680]	valid_0's rmse: 1.854
[700]	valid_0's rmse: 1.85361
[720]	valid_0's rmse: 1.85352
[740]	valid_0's rmse: 1.85335
[760]	valid_0's rmse: 1.85362
[780]	valid_0's rmse: 1.85391
[800]	valid_0's rmse: 1.85382
[820]	valid_0's rmse: 1.85348
[840]	valid_0's rmse: 1.85309
[860]	valid_0's rmse: 1.85334
[880]	valid_0's rmse: 1.85304
[900]	valid_0's rmse: 1.85309
[920]	valid_0's rmse: 1.85249
[940]	valid_0's rmse: 1.85235
[960]	valid_0's rmse: 1.85226
[980]	valid_0's rmse: 1.85217
[1000]	valid_0's rmse: 1.85056
[1020]	valid_0's rmse: 1.85068
[1040]	valid_0's rmse: 1.85003
[1060]	valid_0's rmse: 1.85003
[1080]	valid_0's rmse: 1.84934
[1100]	valid_0's rmse: 1.849
[1120]	valid_0's rmse: 1.84897
[1140]	valid_0's rmse: 1.84842
[1160]	valid_0's rmse: 1.84848
[1180]	valid_0's rmse: 1.84786
[1200]	valid_0's rmse: 1.84847
[1220]	valid_0's rmse: 1.84862
[1240]	valid_0's rmse: 1.8483
[1260]	valid_0's rmse: 1.84751
[1280]	valid_0's rmse: 1.84742
[1300]	valid_0's rmse: 1.84758
[1320]	valid_0's rmse: 1.84697
[1340]	valid_0's rmse: 1.84667
[1360]	valid_0's rmse: 1.84597
[1380]	valid_0's rmse: 1.84596
[1400]	valid_0's rmse: 1.84598
[1420]	valid_0's rmse: 1.84494
[1440]	valid_0's rmse: 1.84517
[1460]	valid_0's rmse: 1.84601
[1480]	valid_0's rmse: 1.84682
[1500]	valid_0's rmse: 1.84648
[1520]	valid_0's rmse: 1.8464
Early stopping, best iteration is:
[1421]	valid_0's rmse: 1.84484
Processing store 2...
Create fake valid data for store 2...
Done creating fake valid data for store 2...
Training model for store 2...
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Total Bins 6795
[LightGBM] [Info] Number of data points in the train set: 3829986, number of used features: 36
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Start training from score 0.823272
Training until validation scores don't improve for 100 rounds
[20]	valid_0's rmse: 4.62916
[40]	valid_0's rmse: 4.13275
[60]	valid_0's rmse: 4.02306
[80]	valid_0's rmse: 4.01313
[100]	valid_0's rmse: 4.00262
[120]	valid_0's rmse: 3.998
[140]	valid_0's rmse: 3.94125
[160]	valid_0's rmse: 3.87195
[180]	valid_0's rmse: 3.80999
[200]	valid_0's rmse: 3.73524
[220]	valid_0's rmse: 3.71064
[240]	valid_0's rmse: 3.67355
[260]	valid_0's rmse: 3.63906
[280]	valid_0's rmse: 3.63039
[300]	valid_0's rmse: 3.59969
[320]	valid_0's rmse: 3.58614
[340]	valid_0's rmse: 3.58714
[360]	valid_0's rmse: 3.57426
[380]	valid_0's rmse: 3.56649
[400]	valid_0's rmse: 3.53589
[420]	valid_0's rmse: 3.51924
[440]	valid_0's rmse: 3.50635
[460]	valid_0's rmse: 3.50487
[480]	valid_0's rmse: 3.50301
[500]	valid_0's rmse: 3.49634
[520]	valid_0's rmse: 3.50218
[540]	valid_0's rmse: 3.50121
[560]	valid_0's rmse: 3.50261
[580]	valid_0's rmse: 3.4941
[600]	valid_0's rmse: 3.48718
[620]	valid_0's rmse: 3.48422
[640]	valid_0's rmse: 3.48461
[660]	valid_0's rmse: 3.47653
[680]	valid_0's rmse: 3.47167
[700]	valid_0's rmse: 3.46881
[720]	valid_0's rmse: 3.46937
[740]	valid_0's rmse: 3.46218
[760]	valid_0's rmse: 3.45835
[780]	valid_0's rmse: 3.4529
[800]	valid_0's rmse: 3.4441
[820]	valid_0's rmse: 3.43373
[840]	valid_0's rmse: 3.43326
[860]	valid_0's rmse: 3.43347
[880]	valid_0's rmse: 3.43702
[900]	valid_0's rmse: 3.43786
[920]	valid_0's rmse: 3.43512
[940]	valid_0's rmse: 3.43171
[960]	valid_0's rmse: 3.43034
[980]	valid_0's rmse: 3.42973
[1000]	valid_0's rmse: 3.42874
[1020]	valid_0's rmse: 3.42994
[1040]	valid_0's rmse: 3.42253
[1060]	valid_0's rmse: 3.42157
[1080]	valid_0's rmse: 3.4164
[1100]	valid_0's rmse: 3.4145
[1120]	valid_0's rmse: 3.41385
[1140]	valid_0's rmse: 3.40892
[1160]	valid_0's rmse: 3.40821
[1180]	valid_0's rmse: 3.40682
[1200]	valid_0's rmse: 3.40304
[1220]	valid_0's rmse: 3.39839
[1240]	valid_0's rmse: 3.39241
[1260]	valid_0's rmse: 3.39184
[1280]	valid_0's rmse: 3.38578
[1300]	valid_0's rmse: 3.38452
[1320]	valid_0's rmse: 3.38089
[1340]	valid_0's rmse: 3.37889
[1360]	valid_0's rmse: 3.37488
[1380]	valid_0's rmse: 3.37298
[1400]	valid_0's rmse: 3.37075
[1420]	valid_0's rmse: 3.37208
[1440]	valid_0's rmse: 3.37336
[1460]	valid_0's rmse: 3.37571
[1480]	valid_0's rmse: 3.37424
[1500]	valid_0's rmse: 3.37298
Early stopping, best iteration is:
[1403]	valid_0's rmse: 3.36944
Processing store 3...
Create fake valid data for store 3...
Done creating fake valid data for store 3...
Training model for store 3...
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Total Bins 6337
[LightGBM] [Info] Number of data points in the train set: 3761592, number of used features: 36
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Start training from score -0.155001
Training until validation scores don't improve for 100 rounds
[20]	valid_0's rmse: 1.72858
[40]	valid_0's rmse: 1.56687
[60]	valid_0's rmse: 1.51972
[80]	valid_0's rmse: 1.50326
[100]	valid_0's rmse: 1.49675
[120]	valid_0's rmse: 1.48986
[140]	valid_0's rmse: 1.48616
[160]	valid_0's rmse: 1.48342
[180]	valid_0's rmse: 1.48199
[200]	valid_0's rmse: 1.48168
[220]	valid_0's rmse: 1.48091
[240]	valid_0's rmse: 1.48022
[260]	valid_0's rmse: 1.4796
[280]	valid_0's rmse: 1.47934
[300]	valid_0's rmse: 1.47962
[320]	valid_0's rmse: 1.48007
[340]	valid_0's rmse: 1.47956
[360]	valid_0's rmse: 1.47975
Early stopping, best iteration is:
[273]	valid_0's rmse: 1.47888
Processing store 4...
Create fake valid data for store 4...
Done creating fake valid data for store 4...
Training model for store 4...
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Total Bins 6693
[LightGBM] [Info] Number of data points in the train set: 3861297, number of used features: 36
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Start training from score 0.116690
Training until validation scores don't improve for 100 rounds
[20]	valid_0's rmse: 2.58596
[40]	valid_0's rmse: 2.39397
[60]	valid_0's rmse: 2.35422
[80]	valid_0's rmse: 2.34325
[100]	valid_0's rmse: 2.34091
[120]	valid_0's rmse: 2.33967
[140]	valid_0's rmse: 2.33154
[160]	valid_0's rmse: 2.32778
[180]	valid_0's rmse: 2.32175
[200]	valid_0's rmse: 2.31959
[220]	valid_0's rmse: 2.3183
[240]	valid_0's rmse: 2.31378
[260]	valid_0's rmse: 2.31078
[280]	valid_0's rmse: 2.30701
[300]	valid_0's rmse: 2.29962
[320]	valid_0's rmse: 2.29741
[340]	valid_0's rmse: 2.29467
[360]	valid_0's rmse: 2.29089
[380]	valid_0's rmse: 2.28768
[400]	valid_0's rmse: 2.28485
[420]	valid_0's rmse: 2.2837
[440]	valid_0's rmse: 2.28197
[460]	valid_0's rmse: 2.28183
[480]	valid_0's rmse: 2.27922
[500]	valid_0's rmse: 2.27703
[520]	valid_0's rmse: 2.27603
[540]	valid_0's rmse: 2.27591
[560]	valid_0's rmse: 2.27609
[580]	valid_0's rmse: 2.27344
[600]	valid_0's rmse: 2.27023
[620]	valid_0's rmse: 2.26772
[640]	valid_0's rmse: 2.26678
[660]	valid_0's rmse: 2.26511
[680]	valid_0's rmse: 2.26357
[700]	valid_0's rmse: 2.2633
[720]	valid_0's rmse: 2.26099
[740]	valid_0's rmse: 2.25911
[760]	valid_0's rmse: 2.25802
[780]	valid_0's rmse: 2.25792
[800]	valid_0's rmse: 2.2569
[820]	valid_0's rmse: 2.25453
[840]	valid_0's rmse: 2.2544
[860]	valid_0's rmse: 2.2543
[880]	valid_0's rmse: 2.25316
[900]	valid_0's rmse: 2.25211
[920]	valid_0's rmse: 2.25302
[940]	valid_0's rmse: 2.25274
[960]	valid_0's rmse: 2.25223
[980]	valid_0's rmse: 2.25223
[1000]	valid_0's rmse: 2.25224
[1020]	valid_0's rmse: 2.25319
[1040]	valid_0's rmse: 2.25219
[1060]	valid_0's rmse: 2.25119
[1080]	valid_0's rmse: 2.25032
[1100]	valid_0's rmse: 2.25024
[1120]	valid_0's rmse: 2.24967
[1140]	valid_0's rmse: 2.24974
[1160]	valid_0's rmse: 2.24861
[1180]	valid_0's rmse: 2.24867
[1200]	valid_0's rmse: 2.24884
[1220]	valid_0's rmse: 2.24959
[1240]	valid_0's rmse: 2.24876
[1260]	valid_0's rmse: 2.24861
[1280]	valid_0's rmse: 2.24949
[1300]	valid_0's rmse: 2.24966
[1320]	valid_0's rmse: 2.24957
[1340]	valid_0's rmse: 2.24931
[1360]	valid_0's rmse: 2.24872
Early stopping, best iteration is:
[1266]	valid_0's rmse: 2.24813
Processing store 5...
Create fake valid data for store 5...
Done creating fake valid data for store 5...
Training model for store 5...
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Total Bins 6752
[LightGBM] [Info] Number of data points in the train set: 3866950, number of used features: 36
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Start training from score 0.358418
Training until validation scores don't improve for 100 rounds
[20]	valid_0's rmse: 3.21241
[40]	valid_0's rmse: 2.85418
[60]	valid_0's rmse: 2.76214
[80]	valid_0's rmse: 2.72762
[100]	valid_0's rmse: 2.71051
[120]	valid_0's rmse: 2.70247
[140]	valid_0's rmse: 2.69433
[160]	valid_0's rmse: 2.68084
[180]	valid_0's rmse: 2.66627
[200]	valid_0's rmse: 2.64203
[220]	valid_0's rmse: 2.63786
[240]	valid_0's rmse: 2.63022
[260]	valid_0's rmse: 2.61779
[280]	valid_0's rmse: 2.6149
[300]	valid_0's rmse: 2.61152
[320]	valid_0's rmse: 2.60624
[340]	valid_0's rmse: 2.59806
[360]	valid_0's rmse: 2.59336
[380]	valid_0's rmse: 2.58922
[400]	valid_0's rmse: 2.58626
[420]	valid_0's rmse: 2.57447
[440]	valid_0's rmse: 2.56852
[460]	valid_0's rmse: 2.56634
[480]	valid_0's rmse: 2.56117
[500]	valid_0's rmse: 2.55735
[520]	valid_0's rmse: 2.55133
[540]	valid_0's rmse: 2.54819
[560]	valid_0's rmse: 2.54658
[580]	valid_0's rmse: 2.54145
[600]	valid_0's rmse: 2.53834
[620]	valid_0's rmse: 2.5329
[640]	valid_0's rmse: 2.53253
[660]	valid_0's rmse: 2.52829
[680]	valid_0's rmse: 2.5302
[700]	valid_0's rmse: 2.52954
[720]	valid_0's rmse: 2.5276
[740]	valid_0's rmse: 2.52542
[760]	valid_0's rmse: 2.5237
[780]	valid_0's rmse: 2.52085
[800]	valid_0's rmse: 2.52053
[820]	valid_0's rmse: 2.51918
[840]	valid_0's rmse: 2.51837
[860]	valid_0's rmse: 2.51742
[880]	valid_0's rmse: 2.51863
[900]	valid_0's rmse: 2.51839
[920]	valid_0's rmse: 2.51787
[940]	valid_0's rmse: 2.51855
[960]	valid_0's rmse: 2.51902
[980]	valid_0's rmse: 2.51843
[1000]	valid_0's rmse: 2.51812
[1020]	valid_0's rmse: 2.51746
[1040]	valid_0's rmse: 2.51679
[1060]	valid_0's rmse: 2.51627
[1080]	valid_0's rmse: 2.51611
[1100]	valid_0's rmse: 2.51611
[1120]	valid_0's rmse: 2.51364
[1140]	valid_0's rmse: 2.51465
[1160]	valid_0's rmse: 2.51299
[1180]	valid_0's rmse: 2.51347
[1200]	valid_0's rmse: 2.51204
[1220]	valid_0's rmse: 2.50908
[1240]	valid_0's rmse: 2.50913
[1260]	valid_0's rmse: 2.5075
[1280]	valid_0's rmse: 2.50547
[1300]	valid_0's rmse: 2.50328
[1320]	valid_0's rmse: 2.50214
[1340]	valid_0's rmse: 2.49904
[1360]	valid_0's rmse: 2.49821
[1380]	valid_0's rmse: 2.49771
[1400]	valid_0's rmse: 2.49845
[1420]	valid_0's rmse: 2.49671
[1440]	valid_0's rmse: 2.49794
[1460]	valid_0's rmse: 2.49662
[1480]	valid_0's rmse: 2.49637
[1500]	valid_0's rmse: 2.49869
[1520]	valid_0's rmse: 2.49786
[1540]	valid_0's rmse: 2.49697
[1560]	valid_0's rmse: 2.49589
[1580]	valid_0's rmse: 2.49601
[1600]	valid_0's rmse: 2.49659
[1620]	valid_0's rmse: 2.49591
[1640]	valid_0's rmse: 2.49607
Early stopping, best iteration is:
[1549]	valid_0's rmse: 2.4955
Processing store 6...
Create fake valid data for store 6...
Done creating fake valid data for store 6...
Training model for store 6...
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Total Bins 6693
[LightGBM] [Info] Number of data points in the train set: 3818312, number of used features: 36
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Start training from score 0.218328
Training until validation scores don't improve for 100 rounds
[20]	valid_0's rmse: 2.49257
[40]	valid_0's rmse: 2.1612
[60]	valid_0's rmse: 2.06998
[80]	valid_0's rmse: 2.03693
[100]	valid_0's rmse: 2.02657
[120]	valid_0's rmse: 2.02158
[140]	valid_0's rmse: 2.01828
[160]	valid_0's rmse: 2.01568
[180]	valid_0's rmse: 2.01058
[200]	valid_0's rmse: 2.0103
[220]	valid_0's rmse: 2.00829
[240]	valid_0's rmse: 2.00437
[260]	valid_0's rmse: 2.01054
[280]	valid_0's rmse: 2.00872
[300]	valid_0's rmse: 2.00559
[320]	valid_0's rmse: 2.0016
[340]	valid_0's rmse: 2.00134
[360]	valid_0's rmse: 1.99738
[380]	valid_0's rmse: 1.99652
[400]	valid_0's rmse: 1.99473
[420]	valid_0's rmse: 1.99315
[440]	valid_0's rmse: 1.98802
[460]	valid_0's rmse: 1.99029
[480]	valid_0's rmse: 1.99149
[500]	valid_0's rmse: 1.99114
[520]	valid_0's rmse: 1.99113
[540]	valid_0's rmse: 1.98852
Early stopping, best iteration is:
[444]	valid_0's rmse: 1.98752
Processing store 7...
Create fake valid data for store 7...
Done creating fake valid data for store 7...
Training model for store 7...
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Total Bins 6577
[LightGBM] [Info] Number of data points in the train set: 3739818, number of used features: 36
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Start training from score 0.118246
Training until validation scores don't improve for 100 rounds
[20]	valid_0's rmse: 1.97348
[40]	valid_0's rmse: 1.77238
[60]	valid_0's rmse: 1.72439
[80]	valid_0's rmse: 1.71246
[100]	valid_0's rmse: 1.70631
[120]	valid_0's rmse: 1.70586
[140]	valid_0's rmse: 1.70247
[160]	valid_0's rmse: 1.6982
[180]	valid_0's rmse: 1.69344
[200]	valid_0's rmse: 1.68925
[220]	valid_0's rmse: 1.68658
[240]	valid_0's rmse: 1.68493
[260]	valid_0's rmse: 1.68125
[280]	valid_0's rmse: 1.67939
[300]	valid_0's rmse: 1.67447
[320]	valid_0's rmse: 1.67344
[340]	valid_0's rmse: 1.67086
[360]	valid_0's rmse: 1.66842
[380]	valid_0's rmse: 1.66796
[400]	valid_0's rmse: 1.66588
[420]	valid_0's rmse: 1.66477
[440]	valid_0's rmse: 1.6618
[460]	valid_0's rmse: 1.65964
[480]	valid_0's rmse: 1.65683
[500]	valid_0's rmse: 1.6551
[520]	valid_0's rmse: 1.65327
[540]	valid_0's rmse: 1.65118
[560]	valid_0's rmse: 1.65029
[580]	valid_0's rmse: 1.64904
[600]	valid_0's rmse: 1.64801
[620]	valid_0's rmse: 1.64584
[640]	valid_0's rmse: 1.64632
[660]	valid_0's rmse: 1.64484
[680]	valid_0's rmse: 1.6436
[700]	valid_0's rmse: 1.6423
[720]	valid_0's rmse: 1.64143
[740]	valid_0's rmse: 1.6413
[760]	valid_0's rmse: 1.64081
[780]	valid_0's rmse: 1.64075
[800]	valid_0's rmse: 1.64066
[820]	valid_0's rmse: 1.63969
[840]	valid_0's rmse: 1.63931
[860]	valid_0's rmse: 1.63841
[880]	valid_0's rmse: 1.63757
[900]	valid_0's rmse: 1.63703
[920]	valid_0's rmse: 1.63628
[940]	valid_0's rmse: 1.63574
[960]	valid_0's rmse: 1.63565
[980]	valid_0's rmse: 1.6358
[1000]	valid_0's rmse: 1.63625
[1020]	valid_0's rmse: 1.63589
[1040]	valid_0's rmse: 1.6356
[1060]	valid_0's rmse: 1.63596
Early stopping, best iteration is:
[969]	valid_0's rmse: 1.63551
Processing store 8...
Create fake valid data for store 8...

In [11]:
alphas = [1.028, 1.023, 1.018]
weights = [1 / len(alphas)] * len(alphas)
sub = 0.

# Load toàn bộ model trước (rất quan trọng để tăng tốc)
models = {
    store_id: lgb.Booster(model_file=f"../dataset/result/model/model_store_{store_id}.lgb")
    for store_id in range(10)
}

cols = [f"d_{tr_last + i}" for i in range(1, 29)]

for icount, (alpha, weight) in enumerate(zip(alphas, weights)):

    te = create_dt(
        is_train=False,
        price_dt=PRICE_DTYPES,
        cal_dt=CAL_DTYPES,
        tr_last=tr_last
    )

    te = add_demandFeature(data=te)

    for tdelta in range(28):
        day = fday + timedelta(days=tdelta)
        print(f"Day {tdelta}: {day}")

        for store_id, model in models.items():

            # Filter data theo store ngay từ đầu → nhanh hơn rất nhiều
            tst = te[
                (te["store_id"] == store_id) &
                (te["date"] >= day - timedelta(days=max_lags)) &
                (te["date"] <= day)
            ].copy()

            if tst.empty:
                continue

            create_fea(tst,lags_fe = [7, 28, 56], wins_fe = [7, 28], std_fe = [28], 
                price_lags_fe = [7], price_wins_fe = [28], price_std_fe = [28])

            tst_day = tst.loc[tst["date"] == day, train_cols]

            if tst_day.empty:
                continue

            te.loc[
                (te["store_id"] == store_id) & (te["date"] == day),
                "sales"
            ] = alpha * model.predict(tst_day)

    # ===== reshape submission =====
    te_sub = te.loc[te.date >= fday, ["id", "sales"]].copy()

    te_sub["F"] = [
        f"d_{tr_last + rank}"
        for rank in te_sub.groupby("id").cumcount() + 1
    ]

    te_sub = te_sub.set_index(["id", "F"]).unstack()["sales"][cols].reset_index()
    te_sub.fillna(0., inplace=True)
    te_sub.sort_values("id", inplace=True)
    te_sub.reset_index(drop=True, inplace=True)

    te_sub.to_csv(f"../dataset/result/stores/submission_all_{icount}.csv", index=False)

    # ===== ensemble =====
    if icount == 0:
        sub = te_sub.copy()
        sub[cols] *= weight
    else:
        sub[cols] += te_sub[cols] * weight

    print(f"Done alpha {alpha}")

# ===== final submission =====
sub["id"] = sub["id"].str.extract(r"^(.+?)_(?:validation|evaluation)$", expand=False)
sub.columns.name = None
sub.set_index("id", inplace=True)
sub.to_csv("../dataset/result/stores/submission_all.csv", index=False)

Day 0: 2016-04-25 00:00:00
Day 1: 2016-04-26 00:00:00
Day 2: 2016-04-27 00:00:00
Day 3: 2016-04-28 00:00:00
Day 4: 2016-04-29 00:00:00
Day 5: 2016-04-30 00:00:00
Day 6: 2016-05-01 00:00:00
Day 7: 2016-05-02 00:00:00
Day 8: 2016-05-03 00:00:00
Day 9: 2016-05-04 00:00:00
Day 10: 2016-05-05 00:00:00
Day 11: 2016-05-06 00:00:00
Day 12: 2016-05-07 00:00:00
Day 13: 2016-05-08 00:00:00
Day 14: 2016-05-09 00:00:00
Day 15: 2016-05-10 00:00:00
Day 16: 2016-05-11 00:00:00
Day 17: 2016-05-12 00:00:00
Day 18: 2016-05-13 00:00:00
Day 19: 2016-05-14 00:00:00
Day 20: 2016-05-15 00:00:00
Day 21: 2016-05-16 00:00:00
Day 22: 2016-05-17 00:00:00
Day 23: 2016-05-18 00:00:00
Day 24: 2016-05-19 00:00:00
Day 25: 2016-05-20 00:00:00
Day 26: 2016-05-21 00:00:00
Day 27: 2016-05-22 00:00:00
Done alpha 1.028
Day 0: 2016-04-25 00:00:00
Day 1: 2016-04-26 00:00:00
Day 2: 2016-04-27 00:00:00
Day 3: 2016-04-28 00:00:00
Day 4: 2016-04-29 00:00:00
Day 5: 2016-04-30 00:00:00
Day 6: 2016-05-01 00:00:00
Day 7: 2016-05-02 00:00:00
Day 8: 2016-05-03 00:00:00
Day 9: 2016-05-04 00:00:00
Day 10: 2016-05-05 00:00:00
Day 11: 2016-05-06 00:00:00
Day 12: 2016-05-07 00:00:00
Day 13: 2016-05-08 00:00:00
Day 14: 2016-05-09 00:00:00
Day 15: 2016-05-10 00:00:00
Day 16: 2016-05-11 00:00:00
Day 17: 2016-05-12 00:00:00
Day 18: 2016-05-13 00:00:00
Day 19: 2016-05-14 00:00:00
Day 20: 2016-05-15 00:00:00
Day 21: 2016-05-16 00:00:00
Day 22: 2016-05-17 00:00:00
Day 23: 2016-05-18 00:00:00
Day 24: 2016-05-19 00:00:00
Day 25: 2016-05-20 00:00:00
Day 26: 2016-05-21 00:00:00
Day 27: 2016-05-22 00:00:00
Done alpha 1.023
Day 0: 2016-04-25 00:00:00
Day 1: 2016-04-26 00:00:00
Day 2: 2016-04-27 00:00:00
Day 3: 2016-04-28 00:00:00
Day 4: 2016-04-29 00:00:00
Day 5: 2016-04-30 00:00:00
Day 6: 2016-05-01 00:00:00
Day 7: 2016-05-02 00:00:00
Day 8: 2016-05-03 00:00:00
Day 9: 2016-05-04 00:00:00
Day 10: 2016-05-05 00:00:00
Day 11: 2016-05-06 00:00:00
Day 12: 2016-05-07 00:00:00
Day 13: 2016-05-08 00:00:00
Day 14: 2016-05-09 00:00:00
Day 15: 2016-05-10 00:00:00
Day 16: 2016-05-11 00:00:00
Day 17: 2016-05-12 00:00:00
Day 18: 2016-05-13 00:00:00
Day 19: 2016-05-14 00:00:00
Day 20: 2016-05-15 00:00:00
Day 21: 2016-05-16 00:00:00
Day 22: 2016-05-17 00:00:00
Day 23: 2016-05-18 00:00:00
Day 24: 2016-05-19 00:00:00
Day 25: 2016-05-20 00:00:00
Day 26: 2016-05-21 00:00:00
Day 27: 2016-05-22 00:00:00
Done alpha 1.018

In [12]:
def rmsse(train, test, forecast):

    #Sort index để phòng bị sai thứ tự
    test = test.sort_index()
    forecast = forecast.sort_index()
    train = train.sort_index()

    #Tính toán RMSSE
    forecast_mse = np.mean((test - forecast)**2, axis=1)
    train_mse = train.apply(
        lambda row: np.mean(np.diff(np.trim_zeros(row.values)) ** 2)
        if len(np.trim_zeros(row.values)) > 1 else 0,
        axis=1
    )
    return np.sqrt(forecast_mse / train_mse)

In [13]:
#Preview dữ liệu forecast
sub.head()

,d_1914,d_1915,d_1916,d_1917,d_1918,d_1919,d_1920,d_1921,d_1922,d_1923,d_1924,d_1925,d_1926,d_1927,d_1928,d_1929,d_1930,d_1931,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,
FOODS_1_001_CA_1,0.922822,0.811001,0.822824,0.785904,0.915815,1.328313,1.246389,1.024716,0.962524,0.949702,0.938302,1.153118,1.421218,1.191220,1.028447,0.950685,0.975551,0.960702,1.142417,1.401162,1.276668,0.969564,0.903751,0.909112,0.931164,1.147825,1.397536,1.284290
FOODS_1_001_CA_2,0.974830,0.806171,0.757667,0.822066,1.033090,1.311104,1.364822,0.822650,0.901199,0.853317,1.086894,0.977091,1.203530,1.378682,0.853421,0.948855,0.896875,0.975631,1.214356,1.480741,1.665203,1.005878,1.081415,1.075092,1.297393,1.287960,1.757292,1.565312
FOODS_1_001_CA_3,0.973566,0.941995,0.754768,0.730472,1.112594,1.156751,0.950512,0.571255,0.699433,0.586315,0.670192,0.962472,1.083832,1.074155,0.823463,0.794522,0.672456,0.668186,0.996177,1.127486,1.340948,0.868287,0.806224,0.699140,0.702269,1.003697,1.099529,1.445079
FOODS_1_001_CA_4,0.360599,0.327967,0.331218,0.331218,0.322565,0.369860,0.439526,0.394384,0.378459,0.387074,0.370291,0.361919,0.417021,0.369896,0.393090,0.366570,0.372903,0.372903,0.337187,0.412592,0.409311,0.398454,0.367001,0.375279,0.385996,0.351403,0.394941,0.392569
FOODS_1_001_TX_1,0.566695,0.582142,0.573857,0.565571,0.303549,0.246318,0.263837,0.497197,0.506626,0.525762,0.404583,0.607421,0.593476,0.426943,0.531234,0.460826,0.420943,0.437724,0.420039,0.446750,0.506627,0.445833,0.410816,0.429133,0.445827,0.449170,0.532910,0.493399

In [14]:
#Xử lý lại tập test để đánh giá
df_valid = pd.read_csv("../dataset/raw/sales_train_evaluation.csv")
cols = [f"d_{i}" for i in range(tr_last + 1, 1942)]

df_valid["id"] = df_valid["id"].str.extract(r"^(.+?)_(?:validation|evaluation)$", expand=False)
df_valid.set_index("id", inplace = True)

test = df_valid[cols]

test.head()

,d_1914,d_1915,d_1916,d_1917,d_1918,d_1919,d_1920,d_1921,d_1922,d_1923,d_1924,d_1925,d_1926,d_1927,d_1928,d_1929,d_1930,d_1931,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,
HOBBIES_1_001_CA_1,0,0,0,2,0,3,5,0,0,1,1,0,2,1,2,2,1,0,2,4,0,0,0,0,3,3,0,1
HOBBIES_1_002_CA_1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,2,1,1,0,0,0,0,0
HOBBIES_1_003_CA_1,0,0,1,1,0,2,1,0,0,0,0,2,1,3,0,0,1,0,1,0,2,0,0,0,2,3,0,1
HOBBIES_1_004_CA_1,0,0,1,2,4,1,6,4,0,0,0,2,2,4,2,1,1,1,1,1,0,4,0,1,3,0,2,6
HOBBIES_1_005_CA_1,1,0,2,3,1,0,3,2,3,1,1,3,2,3,2,2,2,2,0,0,0,2,1,0,0,2,1,0

In [15]:
# 1. Đổi đuôi id
train = df_valid.filter(like="d_")
train.head()

,d_1,d_2,d_3,d_4,d_5,d_6,d_7,d_8,d_9,d_10,d_11,d_12,d_13,d_14,d_15,d_16,d_17,d_18,d_19,d_20,d_21,d_22,d_23,d_24,d_25,...,d_1917,d_1918,d_1919,d_1920,d_1921,d_1922,d_1923,d_1924,d_1925,d_1926,d_1927,d_1928,d_1929,d_1930,d_1931,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
HOBBIES_1_001_CA_1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,2,0,3,5,0,0,1,1,0,2,1,2,2,1,0,2,4,0,0,0,0,3,3,0,1
HOBBIES_1_002_CA_1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,2,1,1,0,0,0,0,0
HOBBIES_1_003_CA_1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,1,0,2,1,0,0,0,0,2,1,3,0,0,1,0,1,0,2,0,0,0,2,3,0,1
HOBBIES_1_004_CA_1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,2,4,1,6,4,0,0,0,2,2,4,2,1,1,1,1,1,0,4,0,1,3,0,2,6
HOBBIES_1_005_CA_1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,3,1,0,3,2,3,1,1,3,2,3,2,2,2,2,0,0,0,2,1,0,0,2,1,0

In [16]:
# Tỷ trọng
item_share = pd.read_csv("../dataset/result/item_share.csv")
item_share.set_index("item_id", inplace = True)

item_share.tail()

                       sales_share
item_id
HOBBIES_2_025_TX_1    8.218128e-08
HOUSEHOLD_1_512_CA_4  6.586242e-08
FOODS_1_079_CA_2      3.263771e-08
FOODS_1_079_CA_3      1.631885e-08
FOODS_2_394_TX_3      0.000000e+00

In [17]:
rmsse_result = rmsse(train, test, sub)

In [18]:
wrmsse = rmsse_result * item_share['sales_share']
wrmsse.sum()

np.float64(0.7769053796444829)